name: learn-github-actions
on:
  push:
    branches: [ develop ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      env:
         SSH_PRIVATE_KEY: ${{ secrets.SSH_PVT_KEY }}
      run: |
          sudo apt-get update -qq
          which ssh-agent || ( sudo apt-get install -qq openssh-client )
          eval $(ssh-agent -s)
          ssh-add <(echo "$SSH_PRIVATE_KEY")
          mkdir -p ~/.ssh && touch ~/.ssh/config
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          ssh ubuntu@204.48.30.132 "ls -lah"
            


