name: learn-github-actions
on:
  push:
    branches: [ main ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 18.156.129.126
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
               whoami
               ls -alh
            


