name: learn-github-actions
on:
  push:
    branches: [ main ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 204.48.30.132
        username: ubuntu
        key: ${{ secrets.SSH_PVT_KEY }}
        port: 22
        script: |
               cd /home/ubuntu
               pwd
               bash deploy.sh
            


